default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogapp2_development

test:
  <<: *default
  database: blogapp2_test

production:
  <<: *default
  database: blogapp2_production
  username: blogapp2
  password: <%= ENV["BLOGAPP2_DATABASE_PASSWORD"] %>
